export const siteURL = process.env.NEXT_PUBLIC_SITE_URL;
export const consumerKey = process.env.NEXT_PUBLIC_WOOCOMMERCE_CONSUMER_KEY;
export const consumerSecret = process.env.NEXT_PUBLIC_WOOCOMMERCE_CONSUMER_SECRET;
export const googleTagManagerKey = process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER;
export const googleMapKey = process.env.NEXT_PUBLIC_GOOGLE_MAP_KEY;
export const googleMapRegion = process.env.NEXT_PUBLIC_GOOGLE_MAP_REGION;
export const algoliaAppId = process.env.NEXT_PUBLIC_ALGOLIA_APP_ID;
export const algoliaApiKey = process.env.NEXT_PUBLIC_ALGOLIA_API_KEY;
export const algoliaWCRestProductsIndex = process.env.NEXT_PUBLIC_ALGOLIA_WC_REST_PRODUCTS_INDEX;
export const mongodbPassword = process.env.MONGODB_PASSWORD;
export const mongodbUsername = process.env.MONGODB_USERNAME;
export const mongodbDB = process.env.MONGODB_DB
export const stripePrimaryKey = process.env.NEXT_PUBLIC_STRIPE_PRIMARY_KEY
export const stripeSecretKey = process.env.STRIPE_SECRET_KEY
export const alphaHost = process.env.NEXT_PUBLIC_ALPHA_HOST
export const frontendDomain = process.env.NEXT_PUBLIC_ALPHA_HOST
export const alphaMerchantId = process.env.NEXT_PUBLIC_ALPHA_MERCHANT_ID
export const alphaSharedSecretKey = process.env.NEXT_PUBLIC_ALPHA_SHARED_SECRET
export const sendGridApiKey=process.env.SEND_GRID_API_KEY
export const sendGridEmailTo=process.env.SEND_GRID_EMAIL_TO
export const gdprCookiesName="sfkshop-gdpr-cookies"
export const klaviyoToken = process.env.NEXT_PUBLIC_KLAVIYO_TOKEN
export const eshopMetaContent = process.env.NEXT_PUBLIC_ESHOP_META_CONTENT
export const metrimoID = process.env.NEXT_PUBLIC_METRIMO_ID
export const skroutzKey = process.env.NEXT_PUBLIC_SKROUTZ_KEY